### ISSUE TITLE
Call Memes by ID

### ISSUE THREAD

**Issue by xnaas** [Gravebot/Gravebot#131]
It would be nice to also be able to call memes via ID from imgflip instead of being limited to custom/names only. This allows anyone to use any meme _and_ be able to call memes by name (when added to the correct file).
- [ ] Call Memes by ID
- [ ] Call Memes by link (if it's parseable)

**Comment by dustinblackman** [comment]
A link would be nice too. Will hopefully be getting to it this week or next.

**Comment by xnaas** [comment]
Closing out another old issue from my account,
