### ISSUE TITLE
Add Trivia

### ISSUE THREAD

**Issue by xnaas** [Gravebot/Gravebot#132]
I think it would be awesome to have the function of trivia. Everybody loves playing trivia!

For an example, you can check out (it's Python) [Red](https://github.com/Twentysix26/Red-DiscordBot/tree/develop).

**Comment by dustinblackman** [comment]
I've added it to the feature list. Thanks. :)

**Comment by etp12** [comment]
I've been putting some work into this one because it sounds like fun! The public Gravebot that is hosted seems to be used by a lot of servers. What do you think is a good limit on the amount of trivia games that are allowed to be played at once? One per channel or maybe even one per server?

**Comment by xnaas** [comment]
Closing out insanely old issue.
