### ISSUE TITLE
addcom, delcom, editcom

### ISSUE THREAD

**Issue by xnaas** [Gravebot/Gravebot#133]
It would be cool to have the ability to add custom commands. Nothing fancy.

Format: `!addcom [command] [stuff for the command to say/do]`

Example: `!addcom wow https://media.giphy.com/media/3oEduOs13P8wqNjFK0/giphy.gif`

Now when I type `!wow` the bot would say `https://media.giphy.com/media/3oEduOs13P8wqNjFK0/giphy.gif`. And it could be anything. An imgur link, a line of text, etc.

That was adding a command. `delcom` seems pretty self-explanatory. `editcom` would follow a similar format but if I typed ``!editcom wow Wow!` it would make the bot say `Wow!` now instead of `https://media.giphy.com/media/3oEduOs13P8wqNjFK0/giphy.gif` when you type `!wow`.

---

I hope that was at least somewhat clear. :) I can clarify as needed.

**Comment by dustinblackman** [comment]
I'd be down for this, but it'll be quite awhile before it's implemented. Once we have mod commands setup then something like this may be doable. :) Thanks!

**Comment by xnaas** [comment]
Closing out more old issues from my account.
