### ISSUE TITLE
Not starting in Ubuntu

### ISSUE THREAD

**Issue by arbelo** [Gravebot/Gravebot#145]
Here's the debug file. Seems to be an issue with sudo npm install not creating ./dist

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.7.3
3 info using node@v5.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle gravebot@2.1.0~prestart: gravebot@2.1.0
6 silly lifecycle gravebot@2.1.0~prestart: no script for prestart, continuing
7 info lifecycle gravebot@2.1.0~start: gravebot@2.1.0
8 verbose lifecycle gravebot@2.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle gravebot@2.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/wadi/Desktop/Gravebot/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle gravebot@2.1.0~start: CWD: /home/wadi/Desktop/Gravebot
11 silly lifecycle gravebot@2.1.0~start: Args: [ '-c', 'node index.js' ]
12 silly lifecycle gravebot@2.1.0~start: Returned: code: 1  signal: null
13 info lifecycle gravebot@2.1.0~start: Failed to exec start script
14 verbose stack Error: gravebot@2.1.0 start: `node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid gravebot@2.1.0
16 verbose cwd /home/wadi/Desktop/Gravebot
17 error Linux 4.2.0-23-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.8.0
20 error npm  v3.7.3
21 error code ELIFECYCLE
22 error gravebot@2.1.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the gravebot@2.1.0 start script 'node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the gravebot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs gravebot
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls gravebot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by dustinblackman** [comment]
Your npm isn't firing postinstall probably due to permission issues. Run `npm postinstall` and you'll be good to go!

**Comment by arbelo** [comment]
I now get this error when attempting to run 'sudo npm run postinstall'

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'postinstall' ]
2 info using npm@3.7.3
3 info using node@v5.8.0
4 verbose run-script [ 'postinstall' ]
5 info lifecycle gravebot@2.1.0~postinstall: gravebot@2.1.0
6 verbose lifecycle gravebot@2.1.0~postinstall: unsafe-perm in lifecycle true
7 verbose lifecycle gravebot@2.1.0~postinstall: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/wadi/Desktop/Gravebot/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
8 verbose lifecycle gravebot@2.1.0~postinstall: CWD: /home/wadi/Desktop/Gravebot
9 silly lifecycle gravebot@2.1.0~postinstall: Args: [ '-c', 'npm run build' ]
10 silly lifecycle gravebot@2.1.0~postinstall: Returned: code: 1  signal: null
11 info lifecycle gravebot@2.1.0~postinstall: Failed to exec postinstall script
12 verbose stack Error: gravebot@2.1.0 postinstall: `npm run build`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
12 verbose stack     at emitTwo (events.js:100:13)
12 verbose stack     at EventEmitter.emit (events.js:185:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
12 verbose stack     at emitTwo (events.js:100:13)
12 verbose stack     at ChildProcess.emit (events.js:185:7)
12 verbose stack     at maybeClose (internal/child_process.js:850:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
13 verbose pkgid gravebot@2.1.0
14 verbose cwd /home/wadi/Desktop/Gravebot
15 error Linux 4.2.0-23-generic
16 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "postinstall"
17 error node v5.8.0
18 error npm  v3.7.3
19 error code ELIFECYCLE
20 error gravebot@2.1.0 postinstall: `npm run build`
20 error Exit status 1
21 error Failed at the gravebot@2.1.0 postinstall script 'npm run build'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the gravebot package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run build
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs gravebot
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls gravebot
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]`

**Comment by dustinblackman** [comment]
Why are you running with sudo? Also the bot uses Node 4, not 5.

**Comment by arbelo** [comment]
If I don't use sudo node tells me to run it with admin privileges, and is it really necessary to downgrade to Node 4? The readme says 
> Install node.js v4.0 or higher

**Comment by dustinblackman** [comment]
You install node and npm incorrectly if it requires `sudo`. And no it's not required, but I can't offer full support with node 5.
