### ISSUE TITLE
Node.js Issues

### ISSUE THREAD

**Issue by Darkfae** [Gravebot/Gravebot#158]
I'm getting errors when running the install about libxmljs and node.js not playing well together. I've got the latest versions of both, and I've tried a couple of different ways with the lib, but get the same errors anyway. It also doesn't seem to want to see the Python install sometimes, but it seems random on when it does or doesn't.

This is for a local install. We wanted to have a personalised name and user icon for the bot.

I've attached the debug file, but it wouldn't take the text itself, so it's zipped.
[npm-debug.zip](https://github.com/Gravebot/Gravebot/files/211200/npm-debug.zip)

**Comment by dustinblackman** [comment]
Unfortunetly neither Graves or I really directly support Windows. We've tried to put together what we know in the setup, but can't help much further. https://github.com/Gravebot/Gravebot#windows

**Comment by Darkfae** [comment]
Ah, so it's Windows specific then. All right. Thanks!
