### ISSUE TITLE
New !emoji's

### ISSUE THREAD

**Issue by weded** [Gravebot/Gravebot#170]
Hey there, I run a community for discord and the !emoji function has turned into a pretty large meme of sorts for us, I was wondering if there are any more new variety's coming out, if not I'd be happy to search and gather / write quite a few of them to be added.

**Comment by dustinblackman** [comment]
If there's any you'd like added feel to make a list or even make a PR!

**Comment by weded** [comment]
http://pastebin.com/iE2GN7Wz

Here's a list of them me and my pal put together - feel free to take your pick. If any need edited / fine tuning feel free to let me know
