### ISSUE TITLE
Not Starting

### ISSUE THREAD

**Issue by BIGDRAG0N** [Gravebot/Gravebot#174]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart gravebot@3.0.0
6 info start gravebot@3.0.0
7 verbose unsafe-perm in lifecycle true
8 info gravebot@3.0.0 Failed to exec start script
9 verbose stack Error: gravebot@3.0.0 start: `node index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid gravebot@3.0.0
11 verbose cwd /home/eric/DiscordBots/AwesomeBot
12 error Linux 4.2.0-27-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
14 error node v4.4.4
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error gravebot@3.0.0 start: `node index.js`
17 error Exit status 1
18 error Failed at the gravebot@3.0.0 start script 'node index.js'.
18 error This is most likely a problem with the gravebot package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node index.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs gravebot
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls gravebot
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by dustinblackman** [comment]
Use npm 3 and try again. Make sure to delete your node_modules folder before running `npm i` again.

**Comment by dustinblackman** [comment]
Stale.
