### ISSUE TITLE
Cannot start the bot

### ISSUE THREAD

**Issue by iBlitz1** [Gravebot/Gravebot#200]
Hi, whenever I try to start the bot I get this error:

http://prntscr.com/c13b1k

**Comment by dustinblackman** [comment]
What version of Node and NPM? That screenshot isn't very detailed, need the entire error message.

**Comment by iBlitz1** [comment]
take a look at this: http://prntscr.com/c14wfq

**Comment by dustinblackman** [comment]
Your post install didn't fire when you ran npm install. Run `npm run postinstall` and you'll be good to go.
