### ISSUE TITLE
Bot fails to start on Ubuntu 14.04

### ISSUE THREAD

**Issue by nikolaaa4** [Gravebot/Gravebot#211]
Using npm start, it shows a bunch of errors and tells me to include error log.
Node js version: v6.4.0
http://pastebin.com/APEHSKuq

**Comment by dustinblackman** [comment]
I haven't tested Gravebot against Node 6, so I can't guarantee anything will work. Gravebot is built to work with Node 4. Try running `node index.js` and see what error you get in return.

**Comment by dustinblackman** [comment]
Stale.
