### ISSUE TITLE
Small English typo

### ISSUE THREAD

**Issue by henhouse** [Gravebot/Gravebot#212]
> GravebotBOT - Today at 2:43 PM
> Why does every rose has it's thorn?

its*

**Comment by dustinblackman** [comment]
What is that from? `!chat`?

**Comment by henhouse** [comment]
Yes sir, sorry, I should have specified.

**Comment by dustinblackman** [comment]
We actually use [Cleverbot](http://cleverbot.com) for our chat implementation. Unfortunately can't do anything about the spelling. Sorry about that!
