### ISSUE TITLE
Bot Failing to Start / Phantomjs Issue

### ISSUE THREAD

**Issue by Jinnial** [Gravebot/Gravebot#213]
I did everything in the tutorial and nothing seemed to work. Here is the debug file it spit out:

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart gravebot@3.0.0
6 info start gravebot@3.0.0
7 verbose unsafe-perm in lifecycle true
8 info gravebot@3.0.0 Failed to exec start script
9 verbose stack Error: gravebot@3.0.0 start: `node index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid gravebot@3.0.0
11 verbose cwd /home/ubuntu/Twatbot
12 error Linux 3.13.0-95-generic
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.4.2
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error gravebot@3.0.0 start: `node index.js`
17 error Exit status 1
18 error Failed at the gravebot@3.0.0 start script 'node index.js'.
18 error This is most likely a problem with the gravebot package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node index.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs gravebot
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls gravebot
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Ohh, and when I run `sudo node index.js` I get this:

![image](https://cloud.githubusercontent.com/assets/10831565/18260036/e5aa8dc2-73af-11e6-8bd5-b5f5fc5b32c4.png)

You can view my setup in my fork of the project. I never changed anything except adding my bot token, key, and api keys.

**Comment by dustinblackman** [comment]
Two things there. Some of the modules only work with npm 3, I'd suggest deleting your `node_modules` folder, running `npm i -g npm@3`, and then `npm i`.

Second is it looks like post install didn't fire. After you've reinstalled if you still get this error, run `npm run postinstall`.

**Comment by Jinnial** [comment]
Thanks. That fixed everything but redis not connecting. Trying to fix that now. I think I just got the IP wrong.

**Comment by Jinnial** [comment]
Well the bot starts now but it gets caught on this:

**Comment by Jinnial** [comment]
Well the bot starts now but it gets caught on this:

**Comment by Jinnial** [comment]
Well the bot starts now but it gets caught on this:

**Comment by Jinnial** [comment]
Well the bot starts now but it gets caught on this:

**Comment by Jinnial** [comment]
Well the bot starts now but it gets caught on this:

**Comment by Jinnial** [comment]
Well the bot starts now but it gets caught on this:

**Comment by Jinnial** [comment]
Well the bot starts now but it gets caught on this:

**Comment by Jinnial** [comment]
Well the bot starts now but it gets caught on this:

**Comment by Jinnial** [comment]
Well the bot starts now but it gets caught on this:

**Comment by Jinnial** [comment]
Well, the bot starts now but it gets caught here: http://imgur.com/a/Fka3P

Sorry about the multiple post, my browser broke.

**Comment by dustinblackman** [comment]
Phantomjs isn't starting. That I can't help with unfortunately. My windows support is bare minimal. You can try installing phantomjs from their [website](http://phantomjs.org/download.html) and see if it'll install any missing dependencies Phantom may need that didn't come down with NPM.

**Comment by Jinnial** [comment]
I will tonight when I get home. If it still does not work I'll let you know since I am running it on linux. I was just connecting to the server via an SSH client.

**Comment by dustinblackman** [comment]
Which version of linux?

**Comment by Jinnial** [comment]
Ubuntu 14.04

**Comment by dustinblackman** [comment]
Followed [this](https://github.com/Gravebot/Gravebot#linux)?

**Comment by Jinnial** [comment]
Yep. I tried both grabbing it from docker and on github and I get the same errors.

**Comment by dustinblackman** [comment]
Docker you shouldn't be having the problem at all, that's the point of Docker. The image is bundled to work on whatever system Docker runs on.

**Comment by Jinnial** [comment]
I'll try it again this afternoon then. Thanks for all the help so far. 

On Sep 7, 2016 10:07 AM, Dustin Blackman <notifications@github.com> wrote:

Docker you shouldn't be having the problem at all, that's the point of Docker. The image is bundled to work on whatever system Docker runs on.

**Comment by Jinnial** [comment]
So, I just redid the docker and that error goes away but I can't figure out how to set up m container with docker as I have never used it before.

**Comment by dustinblackman** [comment]
There's tutorials that can help with that. Googling around for "running a container with docker-compose" should be simple enough!
