### ISSUE TITLE
Failed at gravebot@3.0.0 start script 'node index.js'

### ISSUE THREAD

**Issue by D48utters** [Gravebot/Gravebot#215]
I have been trying the tutorial way and looking at closed and opened issues for solutions so here is my debug info 
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.1.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle gravebot@3.0.0~prestart: gravebot@3.0.0
6 silly lifecycle gravebot@3.0.0~prestart: no script for prestart, continuing
7 info lifecycle gravebot@3.0.0~start: gravebot@3.0.0
8 verbose lifecycle gravebot@3.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle gravebot@3.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Butters\Documents\Gravebot-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\Butters\AppData\Roaming\npm
10 verbose lifecycle gravebot@3.0.0~start: CWD: C:\Users\Butters\Documents\Gravebot-master
11 silly lifecycle gravebot@3.0.0~start: Args: [ '/d /s /c', 'node index.js' ]
12 silly lifecycle gravebot@3.0.0~start: Returned: code: 1  signal: null
13 info lifecycle gravebot@3.0.0~start: Failed to exec start script
14 verbose stack Error: gravebot@3.0.0 start: `node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid gravebot@3.0.0
16 verbose cwd C:\Users\Butters\Documents\Gravebot-master
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.1.1
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error gravebot@3.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the gravebot@3.0.0 start script 'node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the gravebot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js
23 error You can get their info via:
23 error     npm owner ls gravebot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

I have deleted the node_modules folder and reinstalled with npm i -g npm@3 and the npm run postinstall. This is what I get from doing that 
> gravebot@3.0.0 postinstall C:\Users\Butters\Documents\Gravebot-master
> npm run build

> gravebot@3.0.0 build C:\Users\Butters\Documents\Gravebot-master
> concurrent 'npm run build-js' 'npm run build-styl'

[0] 'np' is not recognized as an internal or external command,
[0] operable program or batch file.
[1] 'run' is not recognized as an internal or external command,
[1] operable program or batch file.
[2] '"build-js'"' is not recognized as an internal or external command,
[2] operable program or batch file.
[3] 'np' is not recognized as an internal or external command,
[3] operable program or batch file.
[4] 'run' is not recognized as an internal or external command,
[4] operable program or batch file.
[5] '"build-styl'"' is not recognized as an internal or external command,
[5] operable program or batch file.
[5] build-styl' exited with code 1
[4] run exited with code 1
[3] np exited with code 1
[2] build-js' exited with code 1
[1] run exited with code 1
[0] np exited with code 1

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Butters\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v5.1.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! gravebot@3.0.0 build: `concurrent 'npm run build-js' 'npm run build-styl'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gravebot@3.0.0 build script 'concurrent 'npm run build-js' 'npm run build-styl''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gravebot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrent 'npm run build-js' 'npm run build-styl'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gravebot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gravebot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Butters\Documents\Gravebot-master\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "postinstall"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! gravebot@3.0.0 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gravebot@3.0.0 postinstall script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gravebot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls gravebot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Butters\Documents\Gravebot-master\npm-debug.log

**Comment by dustinblackman** [comment]
Two problems there. First is Gravebot is tested with Node 4, not 5. So you may run in to problems I won't recognize. The second is Windows. We try to have what we can for Windows support setup, but it's honestly minimal and most users will have to just figure it out on their own. 

The first problem doesn't show any real error, just that somethings gone wrong. The second problem is window not liking the single quotes I think in the concurrently command.

**Comment by D48utters** [comment]
I am going to try using the windows bash client when I get home today. With the recent windows anniversary update they added a Linux service that I can run bash on

**Comment by D48utters** [comment]
So I have install bash with the windows 10 anniversary update. It says it is Bash on Ubunto. I followed the instructions for linux self-host and it fails at npm install. when I tell it npm install I get this error:

npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/home/D48utters/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.4.0+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/D48utters
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/D48utters/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/D48utters/npm-debug.log
npm ERR! not ok code 0

Also this is coming from the root directory

**Comment by D48utters** [comment]
Ok I got past this but now when I use `npm start` I get this error:

root@DESKTOP-LEF3LP5:/mnt/c/Users/Butters/Documents/Gravebot-master# npm start

> gravebot@3.0.0 start /mnt/c/Users/Butters/Documents/Gravebot-master
> node index.js


/mnt/c/Users/Butters/Documents/Gravebot-master/index.js:5
  console.log(chalk.cyan(`[${moment().format('YYYY-MM-DD HH:mm:ss')}] Booting
                         ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

I have tried using `sudo apt-get install nodejs-legacy` and it says that it installed so I am at a loss

**Comment by dustinblackman** [comment]
Postinstall didn't fire after installation. `npm run postinstall`.

**Comment by D48utters** [comment]
when I run `npm run postinstall` this error happens:

root@DESKTOP-LEF3LP5:/mnt/c/Users/Butters/Documents/Gravebot-master# npm run postinstall

> gravebot@3.0.0 postinstall /mnt/c/Users/Butters/Documents/Gravebot-master
> npm run build


> gravebot@3.0.0 build /mnt/c/Users/Butters/Documents/Gravebot-master
> concurrent 'npm run build-js' 'npm run build-styl'

sh: 1: concurrent: not found

npm ERR! Linux 3.4.0+
npm ERR! argv "/root/.nvm/versions/node/v4.0.0/bin/node" "/root/.nvm/versions/node/v4.0.0/bin/npm" "run" "build"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! gravebot@3.0.0 build: `concurrent 'npm run build-js' 'npm run build-styl'`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the gravebot@3.0.0 build script 'concurrent 'npm run build-js' 'npm run build-styl''.
npm ERR! This is most likely a problem with the gravebot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrent 'npm run build-js' 'npm run build-styl'
npm ERR! You can get their info via:
npm ERR!     npm owner ls gravebot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/Butters/Documents/Gravebot-master/npm-debug.log

npm ERR! Linux 3.4.0+
npm ERR! argv "/root/.nvm/versions/node/v4.0.0/bin/node" "/root/.nvm/versions/node/v4.0.0/bin/npm" "run" "postinstall"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! gravebot@3.0.0 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gravebot@3.0.0 postinstall script 'npm run build'.
npm ERR! This is most likely a problem with the gravebot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls gravebot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/Butters/Documents/Gravebot-master/npm-debug.log

Any ideas?

**Comment by D48utters** [comment]
So I went in am manually ran the dockerfile scrpits and everything worked to i tried to run the `npm run postinstall` to which it gives this error:

root@DESKTOP-LEF3LP5:/mnt/c/Users/Butters/Documents/Gravebot-master# npm run postinstall
npm ERR! Linux 3.4.0+
npm ERR! argv "/root/.nvm/versions/node/v4.0.0/bin/node" "/root/.nvm/versions/node/v4.0.0/bin/npm" "run" "postinstall"
npm ERR! node v4.0.0
npm ERR! npm  v3.10.3

npm ERR! missing script: postinstall
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/Butters/Documents/Gravebot-master/npm-debug.log

**Comment by dustinblackman** [comment]
Are you screwing around with the package.json or running that in something other then the projects root directly? Because the `postinstall` script [isn't missing](https://github.com/Gravebot/Gravebot/blob/master/package.json#L89).

**Comment by D48utters** [comment]
I had not messed with the package.json but after looking with notepad++ I found that it was missing from mine so I am going to get the one from github and try again after my movie

**Comment by dustinblackman** [comment]
That's really, really odd. That the script shouldn't be missing. That line has been in there for months. Have you checked out a super old commit or something like that?

**Comment by D48utters** [comment]
I don't believe so but I may have. I am heading to the movies so I'll try
it when I get back

**Comment by D48utters** [comment]
So after runing the postinstall and trying to do `npm start` I get this error:

root@DESKTOP-LEF3LP5:/mnt/c/Users/Butters/Documents/Gravebot-master# npm start

> gravebot@3.0.0 start /mnt/c/Users/Butters/Documents/Gravebot-master
> node index.js

[2016-09-26 18:12:15] Booting...
[2016-09-26 18:12:20] Express listening on port 6379
[2016-09-26 18:12:20] Starting horseman/phantomjs
/mnt/c/Users/Butters/Documents/Gravebot-master/node_modules/redis/lib/createClient.js:60
            throw new RangeError('The redis url must begin with slashes "//" or contain slashes after the redis protocol');
            ^

RangeError: The redis url must begin with slashes "//" or contain slashes after the redis protocol
    at createClient (/mnt/c/Users/Butters/Documents/Gravebot-master/node_modules/redis/lib/createClient.js:60:19)
    at Object.exports.createClient (/mnt/c/Users/Butters/Documents/Gravebot-master/node_modules/redis/index.js:1081:41)
    at Object.<anonymous> (/mnt/c/Users/Butters/Documents/Gravebot-master/dist/redis.js:41:32)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/mnt/c/Users/Butters/Documents/Gravebot-master/dist/commands/user.js:12:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /mnt/c/Users/Butters/Documents/Gravebot-master/dist/commands/index.js:27:10
    at _map (/mnt/c/Users/Butters/Documents/Gravebot-master/node_modules/ramda/dist/ramda.js:262:27)
    at map (/mnt/c/Users/Butters/Documents/Gravebot-master/node_modules/ramda/dist/ramda.js:5959:20)
    at /mnt/c/Users/Butters/Documents/Gravebot-master/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/mnt/c/Users/Butters/Documents/Gravebot-master/node_modules/ramda/dist/ramda.js:473:22)
    at Object.<anonymous> (/mnt/c/Users/Butters/Documents/Gravebot-master/dist/commands/index.js:26:59)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/mnt/c/Users/Butters/Documents/Gravebot-master/dist/index.js:25:17)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/mnt/c/Users/Butters/Documents/Gravebot-master/index.js:10:3)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

npm ERR! Linux 3.4.0+
npm ERR! argv "/root/.nvm/versions/node/v4.0.0/bin/node" "/root/.nvm/versions/node/v4.0.0/bin/npm" "start"
npm ERR! node v4.0.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! gravebot@3.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gravebot@3.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gravebot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gravebot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gravebot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/Butters/Documents/Gravebot-master/npm-debug.log

**Comment by dustinblackman** [comment]
You have your redis config setup? Looks like you entered it correctly.

I'm going to close this issue. The majority of problems you're facing aren't Gravebot specific but node and configuration. If you come across anything that looks like is broken in the bot itself, feel free to open an new issue! Thanks.
