### ISSUE TITLE
Can Gravebot create a server?

### ISSUE THREAD

**Issue by Sanszy23** [Gravebot/Gravebot#217]
Crazy I know, but can it? Like with some presets that a User can use

**Comment by Gravestorm** [comment]
Discord API has the possibility, but you'd need to contact Discord developers with a valid reason to get whitelisted and be able to actually create them.
https://discordapp.com/developers/docs/resources/guild#create-guild

**Comment by dustinblackman** [comment]
It's rare that we'll get approved, let alone a lot of other accounts. Going to close this.
