### ISSUE TITLE
About the command prefix

### ISSUE THREAD

**Issue by BaraaMe** [Gravebot/Gravebot#229]
Is it possible to allow us to customize the command prefix for our own servers?
It's just that a lot of bots share some prefixes, I find myself limiting what bots I can use based on which ones allow us to change the prefix.

e.g. Instead of !, maybe we can use /, //, or even customize it as needed.

Thanks.

**Comment by dustinblackman** [comment]
See config example. https://github.com/Gravebot/Gravebot/blob/master/config.js.example#L3

**Comment by BaraaMe** [comment]
Right, thanks, but will I have to fill in the entire config.js? Or can I use the default one and just change what I need?

**Comment by dustinblackman** [comment]
Just fill in the ones marked required.
