### ISSUE TITLE
Gravebot is in my server and was working, but has suddenly stopped answering

### ISSUE THREAD

**Issue by Chubiniel** [Gravebot/Gravebot#234]
He won't answer to any command. Odd, I was using it up until this evening. Any ideas? Thanks in advance!

**Comment by dustinblackman** [comment]
This is not something to post on Github, but rather on the [Discord channel](https://discord.gg/k5Kxrc6) for Gravebot. I'm not seeing any problems on any of the servers I have Gravebot running, but I've given it a reboot just incase. Give it a few minutes and try again.

**Comment by Chubiniel** [comment]
Sorry about that and thanks! That must've fixed it!
