### ISSUE TITLE
Bot gives error on start and exits

### ISSUE THREAD

**Issue by Jerlag01** [Gravebot/Gravebot#253]
I'm getting this error when executing npm install:
https://pastebin.com/M7L5itCR

**Comment by Jerlag01** [comment]
@dustinblackman @PhunStyle @TobiTenno @etp12 @RoobieBoobieee 
Can you guys please give support

**Comment by dustinblackman** [comment]
Pinging for support isn't how things are done on Github. Be patient until were available.

Your experiencing some kind of permissions issue when attempting to build `node-inspector`, likely an issue you should be opening with them. Node inspector isn't required however to run Gravebot, you can remove it from the dependencies if you wish.

If you'd like to figure it out, open an issue at node-inspector if anyone is still maintaining it.

**Comment by TobiTenno** [comment]
why did you even ping me? I've never done anything on here...
