### ISSUE TITLE
!! Command

### ISSUE THREAD

**Issue by dustinblackman** [Gravebot/Gravebot#53]
`!! text` Would prefix the users last message plus add whatever on the end. This is useful for if you forget to write something for a command. Make sure the previous command is trimmed first.

```
!lol counters ekko
!! mid
```

**Comment by etp12** [comment]
I'll try to put some work into this one, if no one else has yet

**Comment by dustinblackman** [comment]
That'd be awesome, thanks!

**Comment by etp12** [comment]
Any thoughts on how to get the command to activate on "!!". Right now I have it working with "!append", but I can't figure out how to get it to trigger from "!!".

**Comment by dustinblackman** [comment]
The prefix gets checked for [here](https://github.com/Gravestorm/Gravebot/blob/master/server.js#L33). You can had something to check for a "double prefix" that'll activate your command.
